   ##############################################################################
 ##                                                                              ##
##    /$$   /$$                               /$$                           /$$   ##
##   | $$  | $$                              | $$                          | $$   ##
##   | $$  | $$ /$$   /$$  /$$$$$$   /$$$$$$ | $$  /$$$$$$  /$$$$$$$   /$$$$$$$   ##
##   | $$$$$$$$| $$  | $$ /$$__  $$ /$$__  $$| $$ |____  $$| $$__  $$ /$$__  $$   ##
##   | $$__  $$| $$  | $$| $$  \ $$| $$  \__/| $$  /$$$$$$$| $$  \ $$| $$  | $$   ##
##   | $$  | $$| $$  | $$| $$  | $$| $$      | $$ /$$__  $$| $$  | $$| $$  | $$   ##
##   | $$  | $$|  $$$$$$$| $$$$$$$/| $$      | $$|  $$$$$$$| $$  | $$|  $$$$$$$   ##
##   |__/  |__/ \____  $$| $$____/ |__/      |__/ \_______/|__/  |__/ \_______/   ##
##             /$$  | $$| $$                                                      ##
##            |  $$$$$$/| $$                                                      ##
##             \______/ |__/                                                      ##
 ##                                                                              ##
   ##############################################################################


# Este é um exemplo de arquivo de configuração do Hyprland.
# Consulte o wiki para obter mais informações.
# https://wiki.hypr.land/Configuring/

# Observe que nem todas as configurações / opções disponíveis estão definidas aqui.
# Para uma lista completa, consulte o wiki

# Você pode dividir esta configuração em vários arquivos
# Crie seus arquivos separadamente e vincule-os a este arquivo assim:
# fonte = /.config/hypr/myColors.conf


# MONITOR
source = modules/monitors.conf

# INICIAR
source = modules/autostart.conf

# VARIAVÉIS
source = modules/env.conf

# PERMISSÕES
source = modules/permissions.conf

# APARÊNCIA
source = modules/decoration.conf
source = modules/animations.conf
source = modules/colors.conf

# ENTRADAS
source = modules/input.conf

# GESTOS
source = modules/gestures.conf

# ATALHOS
source = modules/binds.conf

# JANELAS
source = modules/windowrules.conf

# ORGANIZAÇÃO
#source = modules/workspaces.conf
source = modules/layout.conf

# OUTROS
source = modules/misc.conf

# HYPRMOD
source = ~/.config/hypr/hyprland-gui.conf


