[General]
# --- Configurações de Ativos ---
background=assets/background.jpg
fontFamily=Google Sans Flex Freeze
fontSize=14

# --- Cores Dinâmicas (Matugen) ---
# Adicionei .hex em todas para garantir que o QML receba o código correto
primaryColor="#76d2f4"
onPrimaryColor="#003544"
backgroundColor="#101416"
textColor="#dfe3e5"
outlineColor="#889297"
errorColor="#ffb4ab"

# Corrigido: Adicionado .hex para evitar que o QML receba valores nulos ou nomes inválidos
surfaceContainer="#1c2022"
surfaceColor="#1c2022"
onSurfaceColor="#dfe3e5"

# --- Configurações extras de comportamento ---
blurRadius=64
cardOpacity=1