plugin {
    dynamic-cursors {
        enabled = true
        mode = stretch
        threshold = 1

        stretch {
            limit = 3000
            function = negative_quadratic
            window = 100
        }

        shake {
            enabled = true
            nearest = false
            threshold = 5.0
            base = 2.0 
            speed = 1.5
            timeout = 2000
            ipc = true
        }

        hyprcursor {
            enabled = true
            nearest = false
        }
    }
}