# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dfe3e5"

# Title color for boxes
theme[title]="#76d2f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#aaccda"

# Background color of selected item in processes box
theme[selected_bg]="#76d2f4"

# Foreground color of selected item in processes box
theme[selected_fg]="#003544"

# Color of inactive/disabled text
theme[inactive_fg]="#bec8cd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ffb873"

# Cpu box outline color
theme[cpu_box]="#889297"

# Memory/disks box outline color
theme[mem_box]="#889297"

# Net up/down box outline color
theme[net_box]="#889297"

# Processes box outline color
theme[proc_box]="#889297"

# Box divider line and small boxes line color
theme[div_line]="#3e484d"

# Temperature graph colors
theme[temp_start]="#aaccda"
theme[temp_mid]="#76d2f4"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#aaccda"
theme[cpu_mid]="#76d2f4"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#aaccda"
theme[free_mid]=""
theme[free_end]="#2d4d5a"

# Mem/Disk cached meter
theme[cached_start]="#ffb873"
theme[cached_mid]=""
theme[cached_end]="#c88239"

# Mem/Disk available meter
theme[available_start]="#76d2f4"
theme[available_mid]=""
theme[available_end]="#399dbd"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#aaccda"
theme[download_mid]="#76d2f4"
theme[download_end]="#ffb873"

# Upload graph colors
theme[upload_start]="#aaccda"
theme[upload_mid]="#76d2f4"
theme[upload_end]="#ffb873"