$image = /home/shane/Imagens/Wallpapers/Evangelion/013.png

$background = rgba(101416ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d3133ff)

$inverse_primary = rgba(006780ff)

$inverse_surface = rgba(dfe3e5ff)

$on_background = rgba(dfe3e5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003544ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(001f28ff)

$on_primary_fixed_variant = rgba(004d61ff)

$on_secondary = rgba(123440ff)

$on_secondary_container = rgba(c7e9f8ff)

$on_secondary_fixed = rgba(001f28ff)

$on_secondary_fixed_variant = rgba(2b4b57ff)

$on_surface = rgba(dfe3e5ff)

$on_surface_variant = rgba(bec8cdff)

$on_tertiary = rgba(4b2800ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(2d1600ff)

$on_tertiary_fixed_variant = rgba(6a3b00ff)

$outline = rgba(889297ff)

$outline_variant = rgba(3e484dff)

$primary = rgba(76d2f4ff)

$primary_container = rgba(399dbdff)

$primary_fixed = rgba(b8eaffff)

$primary_fixed_dim = rgba(76d2f4ff)

$scrim = rgba(000000ff)

$secondary = rgba(aaccdaff)

$secondary_container = rgba(2d4d5aff)

$secondary_fixed = rgba(c6e8f7ff)

$secondary_fixed_dim = rgba(aaccdaff)

$shadow = rgba(000000ff)

$source_color = rgba(399dbdff)

$surface = rgba(101416ff)

$surface_bright = rgba(353a3cff)

$surface_container = rgba(1c2022ff)

$surface_container_high = rgba(262b2dff)

$surface_container_highest = rgba(313538ff)

$surface_container_low = rgba(181c1eff)

$surface_container_lowest = rgba(0a0f11ff)

$surface_dim = rgba(101416ff)

$surface_tint = rgba(76d2f4ff)

$surface_variant = rgba(3e484dff)

$tertiary = rgba(ffb873ff)

$tertiary_container = rgba(c88239ff)

$tertiary_fixed = rgba(ffdcbfff)

$tertiary_fixed_dim = rgba(ffb873ff)
