##############
### LAYOUT ###
##############

general {
    layout = scrolling
}

# Veja https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = false # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# Veja https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = slave
    new_on_active = before
    mfact = 0.6
}

scrolling {
    follow_focus = true
    follow_min_visible = 0.0
    focus_fit_method = 1
    column_width = 0.75
    explicit_column_widths = 0.25, 0.5, 0.75, 1.0
}