#####################
### MISCELLANEOUS ###
#####################

# Veja em https://wiki.hypr.land/Configuring/Variables/#misc

misc {
    # force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    animate_mouse_windowdragging = true
    animate_manual_resizes = true
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    focus_on_activate = true

    # Frame Rate variavél
    vfr = false

    font_family = "GeistMono Nerd Font Mono"

    # Enable window swallowing
    enable_swallow = false
    swallow_regex = ^(kitty|firefox)$
}

ecosystem:no_donation_nag = 1

xwayland:force_zero_scaling = 1