###############
### JANELAS ###
###############

# Veja https://wiki.hypr.land/Configuring/Window-Rules/ for more
# Veja https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Faça com que as janelas não fixem workspace ao abrir
windowrule = workspace unset, match:class ^$, match:title ^$

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule = size 420 480, float yes, center yes, match:class hyprland-share-picker

windowrule = float yes, match:class steam
windowrule = size 1280 720, center yes, match:title ^Steam$

windowrule = float yes, center yes, size 720 720, match:class python3, match:title ^(ACCELA|Settings)$

windowrule = float yes, center yes, size 1280 720, match:class DivAcerManagerMax

windowrule = float yes, center yes, size 550 600, match:class (org.gnome.Calculator|blueman-manager|com.network.manager)

windowrule = float yes, center yes, size 760 600, match:class org.pulseaudio.pavucontrol

windowrule = float yes, center yes, size 1360 768, match:class ^(Spotify|spotify)$

windowrule = float yes, center yes, size 800 600, match:class (org.gnome.Calendar|org.gnome.Weather|org.gnome.Calculator|org.gnome.clocks)

# Layers

layerrule = ignore_alpha 0.69, blur yes, blur_popups yes, match:namespace (waybar|rofi|swayosd|hypr-dock|dock-popup|swaync-control-center|swaync-notification-window)

layerrule = dim_around yes, match:namespace swaync-control-center

layerrule = animation popin, match:namespace dock-popup

layerrule = animation fade, match:namespace (selection|awww-daemon|logout_dialog|hyprpicker)

layerrule = blur yes, match:namespace logout_dialog

layerrule = dim_around yes, match:namespace rofi
