[config]

################
## PRINCIPAIS ##
################

[templates.hyprland]
input_path = './templates/hyprland-colors.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.hyprlock]
input_path = './templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.css]
input_path = './templates/css-colors.css'
output_path = '~/.cache/matugen/colors/colors.css'
post_hook = '~/.config/scripts/css-linker/css-linker.sh'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/menus/themes/shared/colors.rasi'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme m3-gtk'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

#################
## SECUNDARIOS ##
#################

[templates.btop]
input_path = './templates/btop-colors.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.micro]
input_path = './templates/micro-colors.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.vesktop]
input_path = './templates/discord-colors.css'
output_path = '~/.config/Vencord/themes/matugen.css'

[templates.sddm]
input_path = './templates/sddm-colors.conf'
output_path = '~/.local/share/sddm/sddm-current/theme.conf'

[templates.slurp]
input_path = './templates/slurp-colors.json'
output_path = '~/.config/scripts/slurp/colors.json'

[templates.pywallfox]
input_path  = './templates/pywallfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = '~/.config/scripts/pywallfox-update/pywallfox-update.sh'
