################
### GESTURES ###
################

# Veja https://wiki.hypr.land/Configuring/Gestures

#gesture = 4, vertical, dispatcher, hymission:toggle,forceall
#gesture = 4, vertical, dispatcher, hymission:toggle,recommand
#gesture = 4, vertical, dispatcher, hymission:open,onlycurrentworkspace
#gesture = 3, vertical, dispatcher, hymission:scroll,layout
gesture = 3, horizontal, workspace